using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Nexora.Core.Interfaces;

namespace Nexora.Core.Entities
{
    [Table("ESignatureNotifications")]
    public class ESignatureNotification : IEntity, ITenantEntity, ISoftDelete, IAuditableEntity
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int TenantId { get; set; }

        public int? DocumentId { get; set; }

        public int? SignerId { get; set; }

        public int? UserId { get; set; }

        [Required]
        [MaxLength(50)]
        public string NotificationType { get; set; } // Email, SMS, Push, InApp

        [Required]
        [MaxLength(20)]
        public string Channel { get; set; } // Email, SMS, WhatsApp

        [MaxLength(255)]
        public string RecipientEmail { get; set; }

        [MaxLength(20)]
        public string RecipientPhone { get; set; }

        [MaxLength(1000)]
        public string ErrorMessage { get; set; }

        [Required]
        [MaxLength(100)]
        public string EventType { get; set; } // DocumentSent, SigningReminder, DocumentCompleted, etc.

        [Required]
        [MaxLength(200)]
        public string Recipient { get; set; } // Email address or phone number

        [MaxLength(200)]
        public string RecipientName { get; set; }

        [Required]
        [MaxLength(300)]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }

        public string MessageTemplate { get; set; } // Template used for the message

        public string TemplateData { get; set; } // JSON data used to populate template

        [Required]
        [MaxLength(50)]
        public string Status { get; set; } // Pending, Sent, Delivered, Failed, Bounced

        public DateTime? SentAt { get; set; }

        public DateTime? DeliveredAt { get; set; }

        public DateTime? ReadAt { get; set; }

        public DateTime? ClickedAt { get; set; }

        [MaxLength(1000)]
        public string FailureReason { get; set; }

        public int RetryCount { get; set; } = 0;

        public int MaxRetries { get; set; } = 3;

        public DateTime? NextRetryAt { get; set; }

        [MaxLength(200)]
        public string ExternalMessageId { get; set; } // Provider's message ID

        [MaxLength(100)]
        public string Provider { get; set; } // SendGrid, Twilio, etc.

        public string ProviderResponse { get; set; } // JSON response from provider

        [MaxLength(50)]
        public string Priority { get; set; } // Low, Normal, High, Urgent

        [MaxLength(10)]
        public string Language { get; set; } = "en";

        [MaxLength(20)]
        public string CalendarType { get; set; } = "Gregorian";

        public bool IsReminder { get; set; } = false;

        public DateTime? ReminderScheduledFor { get; set; }

        public int? ReminderSequence { get; set; } // 1st reminder, 2nd reminder, etc.

        public bool IsAutoGenerated { get; set; } = true;

        public bool RequiresUserAction { get; set; } = false;

        [MaxLength(500)]
        public string ActionUrl { get; set; } // URL for user action (signing, viewing, etc.)

        public string ActionData { get; set; } // JSON data for the action

        public DateTime? ExpiresAt { get; set; }

        public bool IsExpired { get; set; } = false;

        public string TrackingData { get; set; } // JSON tracking information

        [MaxLength(100)]
        public string CampaignId { get; set; } // For tracking notification campaigns

        public string PersonalizationData { get; set; } // JSON personalization data

        public bool IsTestNotification { get; set; } = false;
        
        public bool EmailSent { get; set; } = false;
        public DateTime? EmailSentAt { get; set; }
        public string? EmailError { get; set; }
        public bool SmsSent { get; set; } = false;
        public DateTime? SmsSentAt { get; set; }
        public string? SmsError { get; set; }
        public DateTime? ScheduledAt { get; set; }

        public DateTime CreatedAt { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string? UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedAt { get; set; }
        public string? DeletedBy { get; set; }

        [ForeignKey("TenantId")]
        public virtual Tenant Tenant { get; set; }

        [ForeignKey("DocumentId")]
        public virtual ESignatureDocument Document { get; set; }

        [ForeignKey("SignerId")]
        public virtual ESignatureSigner Signer { get; set; }

        [ForeignKey("UserId")]
        public virtual User User { get; set; }
    }
}
